export type MealGoal = "Weight Loss" | "Maintain Weight" | "Muscle Gain" | "Healthy Eating";
export type MealDiet = "Vegetarian" | "Vegan" | "Non-Vegetarian" | "Pescatarian";
export type MealsPerDayCount = 3 | 4 | 5 | 6;
export type MealAllergy = "Nuts" | "Dairy" | "Gluten" | "Eggs" | "Shellfish";
export type MealCuisine = "Indian" | "Italian" | "American" | "Mexican" | "Chinese" | "Any";

export interface UserPreferences {
  userId: string;
  goal: MealGoal;
  diet: MealDiet;
  mealsPerDay: MealsPerDayCount;
  allergies: MealAllergy[];
  cuisines: MealCuisine[];
  updatedAt?: any; // Firestore serverTimestamp
}

export interface MealPlan {
  id: string;
  userId: string;
  planName: string;
  daysCount: number; // 1, 3, or 7
  createdAt: any; // Date or Firestore timestamp
}

export type MealType = "Breakfast" | "Lunch" | "Dinner" | "Snack";

export interface MealPlanItem {
  id: string;
  planId: string;
  userId: string;
  dayNumber: number;
  mealType: MealType;
  recipeId: string | null; // Null for synthetic recipe generated by AI
  recipeTitle: string;
  recipeImageUrl: string;
  calories: number;
  prepTime: number; // In minutes
  ingredients: string[];
  steps: string[];
}

export interface GroceryItem {
  ingredient: string;
  quantity: string;
}
